// <auto-generated />
using EmailPermissãoClientes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmailPermissãoClientes.Migrations
{
    [DbContext(typeof(PermissaoDbContext))]
    [Migration("20241101234029_FK na permissaoCliente")]
    partial class FKnapermissaoCliente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmailPermissãoClientes.Models.PermissaoCliente", b =>
                {
                    b.Property<int>("ClientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientID"));

                    b.Property<int>("EnviarParaID1")
                        .HasColumnType("int");

                    b.Property<int>("FormaEnvioRmID1")
                        .HasColumnType("int");

                    b.Property<bool>("Permitido")
                        .HasColumnType("bit");

                    b.Property<int>("TipoEmailID1")
                        .HasColumnType("int");

                    b.HasKey("ClientID");

                    b.HasIndex("EnviarParaID1");

                    b.HasIndex("FormaEnvioRmID1");

                    b.HasIndex("TipoEmailID1");

                    b.ToTable("permissaoClientes");
                });

            modelBuilder.Entity("EmailPermissãoClientes.Models.PermissaoEnviarPara", b =>
                {
                    b.Property<int>("EnviarParaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnviarParaID"));

                    b.Property<string>("Descrição")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EnviarParaID");

                    b.ToTable("permissaoEnviarPara");
                });

            modelBuilder.Entity("EmailPermissãoClientes.Models.PermissaoFormaEnvio", b =>
                {
                    b.Property<int>("FormaEnvioRmID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormaEnvioRmID"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FormaEnvioRmID");

                    b.ToTable("permissaoFormaEnvios");
                });

            modelBuilder.Entity("EmailPermissãoClientes.Models.PermissaoTipo", b =>
                {
                    b.Property<int>("TipoEmailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoEmailID"));

                    b.Property<string>("Descrição")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoEmailID");

                    b.ToTable("permissaoTipos");
                });

            modelBuilder.Entity("EmailPermissãoClientes.Models.PermissaoCliente", b =>
                {
                    b.HasOne("EmailPermissãoClientes.Models.PermissaoEnviarPara", "EnviarParaID")
                        .WithMany()
                        .HasForeignKey("EnviarParaID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmailPermissãoClientes.Models.PermissaoFormaEnvio", "FormaEnvioRmID")
                        .WithMany()
                        .HasForeignKey("FormaEnvioRmID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmailPermissãoClientes.Models.PermissaoTipo", "TipoEmailID")
                        .WithMany()
                        .HasForeignKey("TipoEmailID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnviarParaID");

                    b.Navigation("FormaEnvioRmID");

                    b.Navigation("TipoEmailID");
                });
#pragma warning restore 612, 618
        }
    }
}
